# fly.toml app configuration file generated for birthdayapp on 2024-12-02T02:11:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'birthdayapp'
primary_region = 'cdg'

[build]

[env]
  PORT = '5001'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
